<?php

return [
    1 => [
        'name' => 'Naturalist Intelligence',
        'icon' => 'fas fa-leaf',
        'description' => 'Understanding and working with nature, plants, and animals',
        'questions' => [
            'I enjoy categorizing things by common traits.',
            'Ecological issues are important to me.',
            'Hiking and camping are enjoyable activities.',
            'I enjoy working on a garden.',
            'I believe preserving our National Park is important.',
            'Putting things in hierarchies makes sense to me.',
            'Animals are important in my life.',
            'My home has a recycling system in place.',
            'I enjoy studying biology, botany and/or zoology.',
            'I spend a great deal of time outdoors.',
        ],
    ],
    2 => [
        'name' => 'Musical Intelligence',
        'icon' => 'fas fa-music',
        'description' => 'Sensitivity to rhythm, pitch, melody, and musical patterns',
        'questions' => [
            'I easily pick up on patterns.',
            'I focus in on noise and sounds.',
            'Moving to a beat is easy for me.',
            "I've always been interested in playing an instrument.",
            'The cadence of poetry intrigues me.',
            'I remember things by putting them in a rhyme.',
            'Concentration is difficult while listening to a radio or television.',
            'I enjoy many kinds of music.',
            'Musicals are more interesting than dramatic plays.',
            'Remembering song lyrics is easy for me.',
        ],
    ],
    3 => [
        'name' => 'Logical Intelligence',
        'icon' => 'fas fa-calculator',
        'description' => 'Mathematical reasoning, logic, and problem-solving abilities',
        'questions' => [
            'I usually pick up on patterns.',
            'I keep my things neat and orderly.',
            'Solving problems comes easily to me.',
            'I get easily frustrated with disorganized people.',
            'I can complete calculations quickly in my head.',
            'Puzzles requiring reasoning are fun.',
            "I can't begin an assignment until all my questions are answered.",
            'Structure helps me be successful.',
            'I find working on a computer spreadsheet or data based rewarding.',
            'Things have to make sense to me or I am dissatisfied.',
        ],
    ],
    4 => [
        'name' => 'Existential Intelligence',
        'icon' => 'fas fa-infinity',
        'description' => "Deep thinking about life's big questions and meaning",
        'questions' => [
            'It is important to see my role in the "big picture" of things.',
            'I enjoy viewing art masterpieces.',
            'Religion is important to me.',
            'I like visiting breathtaking sites in nature.',
            'Relaxation and meditation exercises are rewarding.',
            'I like reading philosophers.',
            'Learning new things is easier when I understand their value.',
            'I wonder if there are other forms of intelligent life in the universe.',
            'Studying history and ancient culture helps give me perspective.',
            'I enjoy viewing art masterpieces.',
        ],
    ],
    5 => [
        'name' => 'Interpersonal Intelligence',
        'icon' => 'fas fa-users',
        'description' => 'Understanding others, social skills, and communication',
        'questions' => [
            'I learn best interacting with others.',
            'The more the merrier.',
            'Study groups are very productive for me.',
            'I enjoy chat rooms.',
            'Participating in politics is important.',
            'Television and radio talk shows are enjoyable.',
            'I am a "team player".',
            'I dislike working alone.',
            'Clubs and extracurricular activities are fun.',
            'I pay attention to social issues and causes.',
        ],
    ],
    6 => [
        'name' => 'Kinesthetic Intelligence',
        'icon' => 'fas fa-running',
        'description' => 'Physical movement, coordination, and hands-on learning',
        'questions' => [
            'I enjoy making things with my hands.',
            'Sitting still for long periods of time is difficult for me.',
            'I enjoy outdoor games and sports.',
            'I value non-verbal communication such as sign language.',
            'A fit body is important for a fit mind.',
            'Arts and crafts are enjoyable pastimes.',
            'Expression through dance is beautiful.',
            'I like working with tools.',
            'I live an active lifestyle.',
            'I learn by doing.',
        ],
    ],
    7 => [
        'name' => 'Verbal Intelligence',
        'icon' => 'fas fa-comments',
        'description' => 'Language skills, writing, and verbal communication',
        'questions' => [
            'I enjoy reading all kinds of materials.',
            'Taking notes helps me remember and understand.',
            'I faithfully contact friends through letters and/or e-mail.',
            'It is easy for me to explain my ideas to others.',
            'I keep a journal.',
            'Word puzzles like crosswords and jumbles are fun.',
            'I write for pleasure.',
            'I enjoy playing with words like puns, anagrams and spoonerisms.',
            'Foreign languages interest me.',
            'Debates and public speaking are activities I like to participate in.',
        ],
    ],
    8 => [
        'name' => 'Intrapersonal Intelligence',
        'icon' => 'fas fa-user',
        'description' => 'Self-awareness, reflection, and understanding yourself',
        'questions' => [
            'I am keenly aware of my moral beliefs.',
            'I learn best when I have an emotional attachment to the subject.',
            'Fairness is important to me.',
            'My attitude affects how I learn.',
            'Social justice issues concern me.',
            'Working alone can be as productive as working in a group.',
            'I need to know why I should do something before I agree to do it.',
            'When I believe in something I give 100% effort to it.',
            'I like to be involved in causes that help others.',
            'I am confident in my beliefs.',
        ],
    ],
    9 => [
        'name' => 'Visual Intelligence',
        'icon' => 'fas fa-eye',
        'description' => 'Spatial awareness, visual thinking, and artistic abilities',
        'questions' => [
            'I can imagine ideas in my mind.',
            'Rearranging a room is fun for me.',
            'I enjoy creating using varied media.',
            'I remember well using graphic organizers.',
            'Performance art can be very gratifying.',
            'Spreadsheets are great for making charts, graphs and tables.',
            'Three dimensional puzzles bring me much enjoyment.',
            'Music videos are very stimulating.',
            'I can recall things in mental pictures.',
            'I am good at reading maps and blueprints.',
        ],
    ],
];
