const TS=6;let cur=1;
function goStep(n){if(n<1||n>TS)return;document.querySelectorAll('.step-panel').forEach(p=>p.classList.remove('active'));document.querySelector(`.step-panel[data-step="${n}"]`).classList.add('active');cur=n;updStepper();window.scrollTo({top:0,behavior:'smooth'});}
function nextStep(){const p=document.querySelector(`.step-panel[data-step="${cur}"]`);let ok=true;p.querySelectorAll('[required]').forEach(f=>{if(!f.value.trim()){f.classList.add('border-red-400');ok=false}else f.classList.remove('border-red-400')});if(!ok){Swal.fire({icon:'warning',title:'Missing Fields',text:'Please fill required fields.',confirmButtonColor:'#163269'});return;}if(cur<TS)goStep(cur+1);}
function prevStep(){if(cur>1)goStep(cur-1);}
function updStepper(){for(let i=1;i<=TS;i++){const c=document.querySelector('.sc'+i),l=document.querySelector('.sl'+i);if(i<cur){c.className='w-9 h-9 rounded-full flex items-center justify-center text-sm font-bold mb-1 sc'+i+' bg-green-500 text-white';c.innerHTML='<i class="fas fa-check"></i>';l.className='text-[10px] font-medium sl'+i+' text-green-600 hidden md:block';}else if(i===cur){c.className='w-9 h-9 rounded-full flex items-center justify-center text-sm font-bold mb-1 sc'+i+' bg-primary text-white';c.innerHTML=i;l.className='text-[10px] font-medium sl'+i+' text-primary hidden md:block';}else{c.className='w-9 h-9 rounded-full flex items-center justify-center text-sm font-bold mb-1 sc'+i+' bg-gray-200 text-gray-400';c.innerHTML=i;l.className='text-[10px] font-medium sl'+i+' text-gray-400 hidden md:block';}if(i<TS){const ln=document.querySelector('.sline'+i);if(ln)ln.className=i<cur?'flex-1 h-0.5 bg-green-500 mt-[-16px] sline'+i:'flex-1 h-0.5 bg-gray-200 mt-[-16px] sline'+i;}}document.getElementById('prevBtn').classList.toggle('hidden',cur===1);document.getElementById('nextBtn').classList.toggle('hidden',cur===TS);document.getElementById('submitBtn').classList.toggle('hidden',cur!==TS);document.getElementById('backBtn').classList.toggle('hidden',cur!==1);}
function tog(s,o){const e=document.getElementById(o);if(s.value==='Other'){e.classList.remove('hidden');e.required=true;e.focus();}else{e.classList.add('hidden');e.required=false;e.value='';}}
document.getElementById('natSel').addEventListener('change',function(){tog(this,'natOther');});
document.getElementById('relSel').addEventListener('change',function(){tog(this,'relOther');});
document.getElementById('crSel')?.addEventListener('change',function(){tog(this,'crOther');});
function addSib(){document.getElementById('noSib').classList.add('hidden');const r=document.createElement('div');r.className='sib-row grid grid-cols-6 gap-2 items-end bg-gray-50 rounded-lg p-3';r.innerHTML='<input type="text" name="sibling_name[]" placeholder="Name" class="col-span-2 rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-primary outline-none"><input type="number" name="sibling_age[]" placeholder="Age" class="rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-primary outline-none"><input type="text" name="sibling_school[]" placeholder="School" class="rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-primary outline-none"><select name="sibling_status[]" class="rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-primary outline-none"><option value="">Status</option><option value="Studying">Studying</option><option value="Working">Working</option><option value="Married">Married</option></select><button type="button" onclick="this.closest(\'.sib-row\').remove()" class="text-red-400 hover:text-red-600"><i class="fas fa-trash"></i></button>';document.getElementById('sibC').appendChild(r);}
function addOrg(){document.getElementById('noOrg').classList.add('hidden');const r=document.createElement('div');r.className='org-row grid grid-cols-4 gap-2 items-end bg-gray-50 rounded-lg p-3';r.innerHTML='<input type="text" name="org_name[]" placeholder="Organization" class="col-span-2 rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-primary outline-none"><input type="text" name="org_designation[]" placeholder="Role" class="rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-primary outline-none"><div class="flex gap-2"><input type="text" name="org_year[]" placeholder="Year" class="rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-primary outline-none flex-1"><button type="button" onclick="this.closest(\'.org-row\').remove()" class="text-red-400 hover:text-red-600"><i class="fas fa-trash"></i></button></div>';document.getElementById('orgC').appendChild(r);}
